/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unit_testjni_MainActivity */

#ifndef _Included_com_unit_testjni_MainActivity
#define _Included_com_unit_testjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unit_testjni_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_unit_testjni_MainActivity_getStringFromNative
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
